server {
    listen 80;
    
    server_name brayangaldom.com www.brayangaldom.com; 

    # Dónde están los archivos de React y cómo leerlos
    location / {
        root /usr/share/nginx/html;
        index index.html;
        
        # Esto es clave para React: Si alguien recarga la página en /contacto, 
        # Nginx no da error 404, sino que le pasa la ruta a React Router.
        try_files $uri $uri/ /index.html; 
    }
}