server {
    # Solo escucha en el 80 interno
    listen 80;
    
    # Ya no importa el dominio aquí, porque el Nginx de la VPS hace ese trabajo
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}