name: Despliegue Profesional con Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Iniciar sesión en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir y subir imagen a GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/brayanb312/mi-sitio-react:latest 

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en la VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # 1. Descarga la imagen
            docker pull ghcr.io/brayanb312/mi-sitio-react:latest
            
            # 2. Detiene y borra el anterior
            docker stop sitio-produccion || true
            docker rm sitio-produccion || true
            
            # 3. Arranca en el puerto 8080 interno y lo hace "inmortal" a los reinicios
            # NOTA: Ya no montamos certificados aquí, el Nginx de la VPS hace ese trabajo
            docker run -d \
              --restart unless-stopped \
              -p 8080:80 \
              --name sitio-produccion \
              ghcr.io/brayanb312/mi-sitio-react:latest